### ISSUE TITLE
updateUi(earthquakes) under 'onLoadFinished' method in EarthquakeActivity.java is not defined ?

### ISSUE THREAD

**Issue by steven7mwesigwa** [udacity/ud843-QuakeReport#106]
Where is the definition for updateUi().

**Comment by pinefoambath** [comment]
[Same problem here. Did you manage to resolve this?]

Update, this fixed it for me 

"
UPDATE....

there seems to be a line of code right above "updateUi(earthquakes);". That line reads...."mAdapter.addAll(earthquakes);", but it is commented out.

if you un-comment that line and comment out the updateUi line the application will load. It seems to be working fine. I can see earthquake info that is consistent with the site info."

**Comment by WD80** [comment]
replace

`updateUi(earthquakes);`

with

`mAdapter.addAll(earthquakes);`

As per the course, a few chapters ago.
