### ISSUE TITLE
project is not even building///

### ISSUE THREAD

**Issue by dinakarj78** [udacity/ud843-QuakeReport#110]

**Comment by Tiam-Abderezai** [comment]
@dasher116 I just had the same problem right now. The way I solved it was I created a new project, and pasted the contents of EarthQuakeActivity.java and earthquake_activity.xml into the corresponding new projects' files and it worked.

**Comment by sagar98cyber** [comment]
> @dasher116 I just had the same problem right now. The way I solved it was I created a new project, and pasted the contents of EarthQuakeActivity.java and earthquake_activity.xml into the corresponding new projects' files and it worked.

This is true!!!!

**Comment by pallaviagrawal1729** [comment]
@dasher116 The best way is to fork the project and open it in Android using Version Control. You will see an error in version Control when the is cloned asking to install and update. Just click it and it will set up all you need. Good to go! :)

**Comment by amanirshad** [comment]
Copying all the contents for the solution. Hope so it works
