### ISSUE TITLE
Failed to reslove com.android.support.appcompat-v7:23.3.0

### ISSUE THREAD

**Issue by heroinedd** [udacity/ud843-QuakeReport#111]
how can i slove this problem???help

**Comment by LaszloLajosT** [comment]
Hi,

When you have this kind of errors, that means you need the right SDK API installed plus information in your "build.grandle(Module:app) file.
Here is a link how you can fix this for some versions: [StackOverFlow](https://stackoverflow.com/questions/29284236/failed-to-resolve-com-android-supportappcompat-v722-and-com-android-supportre)

Here is an example of errors.
![Version problem](https://user-images.githubusercontent.com/57297360/77772264-c050e900-703f-11ea-87cd-ab51f78dfd43.png)

This app will run but will have issues because compileSdkVersion + targetSdkVersion is higher version than the support library's "version" (com.android.support:appcombat-v7:23.4.0).
In my case, I have to implement AndroidX support library instead of v7 support library. (implementation 'androidx.appcompat:appcompat:1.1.0')

**Comment by codershashi** [comment]
@LaszloLajosT I'm also stuck can you please help ,thank you !

This is what I'm getting :

`
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example.android.quakereport"
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
}

`

**Comment by LaszloLajosT** [comment]
> @LaszloLajosT I'm also stuck can you please help ,thank you !
> 
> This is what I'm getting :

Let me ask you something:
Did you open the project from Udacity or did you create a new project and you copy&paste all the code?

**Comment by codershashi** [comment]
> > @LaszloLajosT I'm also stuck can you please help ,thank you !
> > This is what I'm getting :
> 
> Let me ask you something:
> Did you open the project from Udacity or did you create a new project and you copy&paste all the code?

First thanks for responding , I downloaded the zip, extracted it to a folder  and then opened it through Android studio ,I'm using the latest updated version of it .

**Comment by LaszloLajosT** [comment]
> > > @LaszloLajosT I'm also stuck can you please help ,thank you !
> > > This is what I'm getting :
> > 
> > Let me ask you something:
> > Did you open the project from Udacity or did you create a new project and you copy&paste all the code?
> 
> First thanks for responding , I downloaded the zip, extracted it to a folder  and then opened it through Android studio ,I'm using the latest updated version of it .

Good. In your case all you need to do is migrate AndroidX.
Check this out: [ How to migrate Android X and why you need it. ](https://medium.com/androiddevelopers/migrating-to-androidx-tip-tricks-and-guidance-88d5de238876)

Don't worry if you don't understand everything in the post first time. I needed time and some experience as well.

**Comment by codershashi** [comment]
> > > > @LaszloLajosT I'm also stuck can you please help ,thank you !
> > > > This is what I'm getting :
> > > 
> > > 
> > > Let me ask you something:
> > > Did you open the project from Udacity or did you create a new project and you copy&paste all the code?
> > 
> > 
> > First thanks for responding , I downloaded the zip, extracted it to a folder  and then opened it through Android studio ,I'm using the latest updated version of it .
> 
> Good. In your case all you need to do is migrate AndroidX.
> Check this out: [ How to migrate Android X and why you need it. ](https://medium.com/androiddevelopers/migrating-to-androidx-tip-tricks-and-guidance-88d5de238876)
> 
> Don't worry if you don't understand everything in the post first time. I needed time and some experience as well.

Thank you very much ,I will go through the link you have provided :)

**Comment by sgm28** [comment]
Hi, 

Another solution that works is updating the Gradle plug version to 4.1.0 and Gradle Version to 6.5. To do this, click on File then click on Project structure. Change Android Gradle Plugin Version to 4.1.0 and Gradle Version to 6.5 click apply then click Okay. Gradle sync should start automatically.
You will get an error message in the Sync panel (bottom right of the screen). To resolve the error message click on the blue link that says, "Add google Maven repository and sync project." Click on the Do refactor button(bottom left hand of the screen). Gradle sync should automatically start now. Voila, you should be able to build and run your application now. 

I link to a YouTube if you have trouble following the steps.
https://youtu.be/eJenlLLMwSs

All credit for the solution goes to this slack post 
https://stackoverflow.com/questions/64409047/gradle-sync-failed-unsupported-method-syncissue-getmultilinemessage-androi


Suggestion for the future all update the Gradle plug version and Gradle version to the latest version found in this documentation 
https://developer.android.com/studio/releases/gradle-plugin

Try to read the slack post link above and understand what is actually going on.

Never Give Up!
