### ISSUE TITLE
App reloading data onto UI

### ISSUE THREAD

**Issue by brunodmn** [udacity/ud843-QuakeReport#113]
Hello guys,

 Here when my app stops and gets back my data is reloading and ADDING on UI again.
 It means that if I pause/stop and resume app, the list will grow with same data. 

 I FIXED by uncomenting line 211 of EarthquakeActivity.java (mAdapter.clear(););

**Comment by SudKul** [comment]
We have upgraded the code in the **lesson-four** branch to AndroidX in this [commit](https://github.com/udacity/ud843-QuakeReport/commit/5685f5c1881b738a394514abedc48dce0f2ad342). We expect students to replicate the similar updates to other branches, where needed. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
