### ISSUE TITLE
Virtual method invocation (null point exception) 

### ISSUE THREAD

**Issue by raziq2001** [udacity/ud843-QuakeReport#115]
Although my code is correct but when i try to call the method from another class. It is showing null pointer exception i have tried static method and also normal object calling method but the error is same what should i do.... When i try to call methods connected to custom adapter this error pops up

**Comment by SudKul** [comment]
We have upgraded the code in the **lesson-four** branch to AndroidX in this [commit](https://github.com/udacity/ud843-QuakeReport/commit/5685f5c1881b738a394514abedc48dce0f2ad342). We expect students to replicate the similar updates to other branches, where needed. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
