### ISSUE TITLE
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler

### ISSUE THREAD

**Issue by Subhadeeep25** [udacity/ud843-QuakeReport#120]

**Comment by sakibguy** [comment]
## Experienced same issue 

Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler

## Sna p
![1](https://user-images.githubusercontent.com/24685590/147098179-4c552301-b76a-41bb-9284-47cb7a6e2312.PNG)

**Comment by SudKul** [comment]
We have upgraded the code in the **lesson-four** branch to AndroidX in this [commit](https://github.com/udacity/ud843-QuakeReport/commit/5685f5c1881b738a394514abedc48dce0f2ad342). We expect students to replicate the similar updates to other branches, where needed. 

Besides, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
