### ISSUE TITLE
Switch statement exercise is probably too hard

### ISSUE THREAD

**Issue by JeremySilverTongue** [udacity/ud843-QuakeReport#53]
Needs syntax example. I assumed students already knew switch statements. Apparently not.

**Comment by tushar-nitave** [comment]
It is simple, they have just assigned different colors to different magnitudes. In to order to reduce code length and complexity they have used Switch Case statements instead of if/else statements.

**Comment by Kvaibhav01** [comment]
The `switch` statement executes one statement from multiple conditions. Checkout the syntax:

    switch(expression){    
    case value1:    
     //code to be executed;    
     break;  //optional  
    case value2:    
     //code to be executed;    
     break;  //optional  
    ......    
        
    default:     
     code to be executed if all cases are not matched;    
    }    

You can learn more in the documentation [here](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html).

**Comment by Munzya** [comment]
the same can also be written using an if/else statement.

there are lots of different ways to write a code which yields the same results.
