### ISSUE TITLE
No earthquake list!

### ISSUE THREAD

**Issue by Kvaibhav01** [udacity/ud843-QuakeReport#76]
I have downloaded the latest state of the app available here. After generating its unsigned APK file and installing it in my phone it always says _No recent earthquakes found_

I've checked my internet connection but it never shows the earthquake list! I've tested the URL http://earthquake.usgs.gov/fdsnws/event/1/query and there it shows the earthquakes in JavaScript format but not in the app.

**Comment by raonid** [comment]
Hi @Kvaibhav01 ! I've got the same problem here. Have you found a solution to it? If yes, could you please share the solution?

Thank you!
