### ISSUE TITLE
URL not showing any earthquakes

### ISSUE THREAD

**Issue by katherinebabineau** [udacity/ud843-QuakeReport#78]
This is the url that I used, and it works: 

https://earthquake.usgs.gov/fdsnws/event/1/query

**Comment by Kvaibhav01** [comment]
Yes, you need to add _https_ protocol and not _http_

**Comment by elmaso** [comment]
Other wise you get a 301 error back in android studio and the app dosen't show any data... it's confusing for the students

**Comment by ghost** [comment]
using http returns a 301 error. Use https instead. Tested
