### ISSUE TITLE
remove <corners android:radius="18dp" />

### ISSUE THREAD

**Issue by Utshaw** [udacity/ud843-QuakeReport#82]
[magnitude_circle.xml](https://github.com/udacity/ud843-QuakeReport/blob/lesson-one/app/src/main/res/drawable/magnitude_circle.xml) creates a shape drawable which is defined as `android:shape="oval"` . After defining this as _oval_, `<corners android:radius="18dp" />` will not cause any effect . **Please** remove this tag as it seems very confusing .

**Comment by Kvaibhav01** [comment]
Agreed. The Android's [official documentation](https://developer.android.com/guide/topics/resources/drawable-resource.html#Shape) about <corners>says 

> Creates rounded corners for the shape. **Applies only when the shape is a rectangle.**
