### ISSUE TITLE
No Earthquake found

### ISSUE THREAD

**Issue by doct0rX** [udacity/ud843-QuakeReport#89]
I was following up with course materials and after making the uribuilder it seems it don't fetch any data! I checked the logcat and found some errors like: 07-05 15:54:08.990 929-955/com.example.android.quakereport E/com.example.android.quakereport.EarthquakeActivity: Error response code: 301

and downloaded the the app and have a different error, in AsyncTask;

Please check if you need to update the content or something;

**Comment by Kvaibhav01** [comment]
Have you used `https` instead of `http`?

**Comment by doct0rX** [comment]
yes worked;
thanks @Kvaibhav01 :)
