### ISSUE TITLE
Not able to reflect the preference chan instantly

### ISSUE THREAD

**Issue by phurba123** [udacity/ud843-QuakeReport#94]
Not able to reflect the preference change instantly on main Activity ,
I guess we have to make the use of bundle and apply it on @Override onResume...just a thought..not sure.
Can you guys help me on this??

_Originally posted by @phurba123 in https://github.com/udacity/ud843-QuakeReport/commit/05190298d7e6a7de21e3beb8f940e133fea67b4c#commitcomment-31180273_

**Comment by Kvaibhav01** [comment]
Hey! Someone replied to your comment there: https://github.com/udacity/ud843-QuakeReport/commit/05190298d7e6a7de21e3beb8f940e133fea67b4c#commitcomment-31181765
