### ISSUE TITLE
error: cannot find symbol method updateUi(List<Earthquake>)

### ISSUE THREAD

**Issue by madhank93** [udacity/ud843-QuakeReport#95]
Getting this error when i am trying to run the Quake report (lesson-three) app. And i don't see the implementation of the method **updateUI**.

Error location: EarthquakeActivity.java (line no. : 143)

**Comment by Kvaibhav01** [comment]
Check out #86 (https://github.com/udacity/ud843-QuakeReport/issues/86#issue-301283716)

**Comment by madhank93** [comment]
Thanks @Kvaibhav01 .
