### ISSUE TITLE
Render problem on adding a new Fragment

### ISSUE THREAD

**Issue by reeshabhranjan** [udacity/ud843-QuakeReport#99]
Hello! I am having a rendering problem on adding a new Fragment. 
`Found cyclical <include> chain: settings_activity includes settings_activity`
. I saw some solutions here: https://stackoverflow.com/q/19119687 and also referred here: https://developer.android.com/guide/components/fragments.html#Adding. I did not quite understand what exactly I am doing wrong.

**Comment by reeshabhranjan** [comment]
This is what my settings_activity.xml contains:
```
<fragment
    android:name="com.example.android.quakereport.SettingsActivity$QuakePreferenceFragment"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.android.quakereport.SettingsActivity"
    tools:layout="@layout/settings_activity">
</fragment>
```

**Comment by jrcmadushanka** [comment]
I got the same issue and fixed it by removing the `tools:layout="@layout/activity_name"`

Not sure if this is a good practice. But it worked on both app and the IDE.
